export const CHOOSE_WINNER = 'CHOOSE_WINNER';
export const SAVE_WINNER = 'SAVE_WINNER';
export const REJECT_WINNER = 'REJECT_WINNER';
export const UPDATE_CONTESTANTS = 'UPDATE_CONTESTANTS';
export const FETCH_CONTESTANTS = 'FETCH_CONTESTANTS';
export const FETCH_CONTESTANTS_SUCCESS = 'FETCH_CONTESTANTS_SUCCESS';
export const FETCH_CONTESTANTS_FAILURE = 'FETCH_CONTESTANTS_FAILURE';
